# Generated by Django 5.0.2 on 2025-06-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_feature_icon_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes from admin/agent regarding this booking', null=True),
        ),
    ]
